name: pre-commit
description: run pre-commit
inputs:
  extra_args:
    description: options to pass to pre-commit run
    required: false
    default: '--all-files'
  ignore_cache:
    description: clean cache before pre-commit run
    required: false
    default: true
runs:
  using: composite
  steps:
  - run: python -m pip install pre-commit
    shell: bash
  - run: which pre-commit
    shell: bash
  - run: python -m pip freeze --local
    shell: bash
  - run: pre-commit install && pre-commit clean
    shell: bash
  - run: |
      # run multiple times to fix all the issues
      pipenv run pre-commit run --all-files
      pipenv run pre-commit run --all-files
      pipenv run pre-commit run --all-files
      pipenv run pre-commit run --all-files
    shell: bash
