name: pre-commit
description: run pre-commit
inputs:
  extra_args:
    description: options to pass to pre-commit run
    required: false
    default: '--all-files'
runs:
  using: composite
  steps:
  - run: python -m pip install pre-commit
    shell: bash
  - run: python -m pip freeze --local
    shell: bash
  - uses: actions/cache@v3
    with:
      path: ~/.cache/pre-commit
      key: pre-commit-3|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml') }}
  - run: |
      # run multiple times to fix all the issues
      pre-commit run --show-diff-on-failure --color=always ${{ inputs.extra_args }} >/dev/null 2>&1 || exit 0
      pre-commit run --show-diff-on-failure --color=always ${{ inputs.extra_args }} >/dev/null 2>&1 || exit 0
      pre-commit run --show-diff-on-failure --color=always ${{ inputs.extra_args }} >/dev/null 2>&1 || exit 0
      pre-commit run --show-diff-on-failure --color=always ${{ inputs.extra_args }} >/dev/null 2>&1 || exit 0
      pre-commit run --show-diff-on-failure --color=always ${{ inputs.extra_args }} >/dev/null 2>&1 || exit 0
    shell: bash
